---
- import_playbook: playbooks/firewall.yaml
- import_playbook: playbooks/clitools.yaml
- import_playbook: playbooks/terminal.yaml
- import_playbook: playbooks/editors.yaml
- import_playbook: playbooks/compilers.yaml
- import_playbook: playbooks/git.yaml
- import_playbook: playbooks/dots.yaml
- import_playbook: playbooks/rust.yaml
- import_playbook: playbooks/cargo_installations.yaml
- import_playbook: playbooks/neovim.yaml
- import_playbook: playbooks/docker.yaml
- import_playbook: playbooks/software.yaml
- import_playbook: playbooks/blacklist.yaml

