- name: Cli
  hosts: localhost
  tasks:
    - name: cli packages
      become: yes
      package:
        state: present
        name:
          - curl
          - jq
          - tmux
          - htop
          - ripgrep
          - tldr
          - git
          - gitk
          - unison
          - nix
