- name: Install Docker
  hosts: localhost
  tasks:
    - name: Install prerequisite packages
      become: yes
      package:
        state: present
        name:
          - ca-certificates
          - curl
          - gpg
    - name: Add docker GPG key
      become: yes
      apt_key:
        state: present
        url: https://download.docker.com/linux/debian/gpg
    - name: Add docker repository
      become: yes
      register: docker_repo
      apt_repository:
        state: present
        repo: deb https://download.docker.com/linux/debian bookworm stable
    - name: update repo
      become: yes
      when: docker_repo.changed
      apt:
        update_cache: true
    - name: Install docker-ce
      become: yes
      apt:
        state: latest
        name: docker-ce
    - name: Add user to docker
      user: name=user groups=docker append=yes
      become: true
- name: Setup UFW for Docker
  hosts: localhost
  tasks:
    - name: route to docker0
      become: yes
      ufw:
        interface_in: lo
        interface_out: docker0
        route: true
        proto: any
        rule: allow
    - name: allow in docker0
      become: yes
      ufw:
        direction: in
        interface: docker0
        proto: any
        rule: allow

