- name: firewall setup
  hosts: localhost
  tasks:
    - name: firewall install
      become: yes
      package:
        state: present
        name:
          - ufw
    - name: firewall setup
      become: yes
      ufw:
        state: enabled
    - name: firewall setup incoming default policy reject
      become: yes
      ufw:
        policy: reject
        direction: incoming
    - name: firewall setup outgoing default policy reject
      become: yes
      ufw:
        state: enabled
        policy: reject
        direction: outgoing
    - name: firewall setup routed default policy reject
      become: yes
      ufw:
        state: enabled
        policy: reject
        direction: routed
    - name: firewall rule ssh
      become: yes
      ufw:
        port: ssh
        proto: tcp
        rule: allow
        direction: out
    - name: firewall rule https
      become: yes
      ufw:
        port: https
        proto: tcp
        rule: allow
        direction: out
    - name: firewall rule dns
      become: yes
      ufw:
        port: 53
        proto: any
        rule: allow
        direction: out
