- name: Cli
  hosts: localhost
  tasks:
    - name: cli packages
      become: yes
      package:
        state: present
        name:
          - keepass2
          - nextcloud-desktop
          - thunderbird
